experiment_name: "cxr_hyda"

trainer:
  fast_dev_run: False
  detect_anomaly: False
  max_epochs: 150
  precision: '16-mixed' # 'bf16-mixed'
  accelerator: "gpu"
  devices:
    - 3
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "cxr_uda"
      name:
      tags:
        - hyper
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        patience: 50
        mode: "min"
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'


chkpt_callback:
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
    dirpath:
    filename:


model:
  class_path: chest_xray.pl_modules.DomainConditionedCXRLitModule
  init_args:
    lr: 0.0001
    min_lr: 1e-6
    w_decay: 0.05 #  0.05
    msim_loss_weight: 1
    use_aux_msim_loss: True

    # primary network
    imagenet_pretrained: True
    num_classes: 5
    task_weights: # calculated from the training set
      - 0.733 # Atelectasis
      - 0.813 # Cardiomegaly
      - 1.000 # Consolidation
      - 0.388 # Effusion
      - 0.956 # Pneumothorax

    # domain branch
    target_domain: # NIH CheXpert VinBrain
    dom_clf_ckpt: <CKPT_PATH>
    domain_encoder:
      class_path: chest_xray.models.domain_classifier.NaiveEncoder
      init_args:
        activation: "ReLU"
        norm_layer: "BatchNorm2d"

    domain_classifier:
      class_path: chest_xray.models.domain_classifier.NaiveClassifier
      init_args:
        num_classes: 3

    # hypernetwork
    hyper_in_size: 64
    hyper_emb: 32
    init_method: 'uniform' # uniform normal
    input_var:  0.11 # input CXR var: ??? domain embeddings var: 0.11




data:
  class_path: chest_xray.data.CXRDataModule
  init_args:
    data_dir: <DATA_DIR>
    unique_patients: False
    target_domain: # NIH CheXpert VinBrain
    batch_size: 32
    num_workers: 16