experiment_name: "domain_classifier"

trainer:
  fast_dev_run: False
  max_epochs: 50
  precision: 'bf16-mixed' # '16-mixed'
  accelerator: "gpu"
  devices:
    - 0
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "mri_uda"
      name:
      tags:
        - domain_clf

chkpt_callback:
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
    dirpath:
    filename:

model:
  class_path: brain_mri.pl_modules.DomainClassifier
  init_args:
    lr: 0.0001
    w_decay: 0.1
    alpha: 2
    msim_on_embeddings: False
    target_domain: <DOMAIN_NAME>


    encoder:
      class_path: brain_mri.models.domain_classifier.GideonsEncoder

    classifier:
      class_path: brain_mri.models.domain_classifier.GideonsMLP
      init_args:
        in_features: 13440
        num_classes: 20 # 21 if training on all domains
        dropout: 0.3

data:
  class_path: brain_mri.data.MRIDataModule
  init_args:
    data_dir: <YOUR_DATA_DIR>
    target_domain: <DOMAIN_NAME>
    ages:
      - 0 #21
      - 100 #80
    batch_size: 32
    num_workers: 4
    pin_memory: False
    balance_by: 'domain'# age domain
